# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:9.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 7070:8080